// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'OButton': typeof import("../front-end/components/o/Button.vue")['default'],
    'OImage': typeof import("../front-end/components/o/Image.vue")['default'],
    'OInput': typeof import("../front-end/components/o/Input.vue")['default'],
    'OLoader': typeof import("../front-end/components/o/Loader.vue")['default'],
    'OoContact': typeof import("../front-end/components/oo/Contact.vue")['default'],
    'OoDarkModeSwitcher': typeof import("../front-end/components/oo/DarkModeSwitcher.vue")['default'],
    'OoWeb3ConnectionInfo': typeof import("../front-end/components/oo/Web3ConnectionInfo.vue")['default'],
    'OooNFTCollection': typeof import("../front-end/components/ooo/NFTCollection.vue")['default'],
    'OooNftCollectionPieces': typeof import("../front-end/components/ooo/NftCollectionPieces.vue")['default'],
    'OooPieces': typeof import("../front-end/components/ooo/Pieces.vue")['default'],
    'OooPiecesData': typeof import("../front-end/components/ooo/piecesData.ts")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyOButton': typeof import("../front-end/components/o/Button.vue")['default'],
    'LazyOImage': typeof import("../front-end/components/o/Image.vue")['default'],
    'LazyOInput': typeof import("../front-end/components/o/Input.vue")['default'],
    'LazyOLoader': typeof import("../front-end/components/o/Loader.vue")['default'],
    'LazyOoContact': typeof import("../front-end/components/oo/Contact.vue")['default'],
    'LazyOoDarkModeSwitcher': typeof import("../front-end/components/oo/DarkModeSwitcher.vue")['default'],
    'LazyOoWeb3ConnectionInfo': typeof import("../front-end/components/oo/Web3ConnectionInfo.vue")['default'],
    'LazyOooNFTCollection': typeof import("../front-end/components/ooo/NFTCollection.vue")['default'],
    'LazyOooNftCollectionPieces': typeof import("../front-end/components/ooo/NftCollectionPieces.vue")['default'],
    'LazyOooPieces': typeof import("../front-end/components/ooo/Pieces.vue")['default'],
    'LazyOooPiecesData': typeof import("../front-end/components/ooo/piecesData.ts")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  }
}
export const OButton: typeof import("../front-end/components/o/Button.vue")['default']
export const OImage: typeof import("../front-end/components/o/Image.vue")['default']
export const OInput: typeof import("../front-end/components/o/Input.vue")['default']
export const OLoader: typeof import("../front-end/components/o/Loader.vue")['default']
export const OoContact: typeof import("../front-end/components/oo/Contact.vue")['default']
export const OoDarkModeSwitcher: typeof import("../front-end/components/oo/DarkModeSwitcher.vue")['default']
export const OoWeb3ConnectionInfo: typeof import("../front-end/components/oo/Web3ConnectionInfo.vue")['default']
export const OooNFTCollection: typeof import("../front-end/components/ooo/NFTCollection.vue")['default']
export const OooNftCollectionPieces: typeof import("../front-end/components/ooo/NftCollectionPieces.vue")['default']
export const OooPieces: typeof import("../front-end/components/ooo/Pieces.vue")['default']
export const OooPiecesData: typeof import("../front-end/components/ooo/piecesData.ts")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyOButton: typeof import("../front-end/components/o/Button.vue")['default']
export const LazyOImage: typeof import("../front-end/components/o/Image.vue")['default']
export const LazyOInput: typeof import("../front-end/components/o/Input.vue")['default']
export const LazyOLoader: typeof import("../front-end/components/o/Loader.vue")['default']
export const LazyOoContact: typeof import("../front-end/components/oo/Contact.vue")['default']
export const LazyOoDarkModeSwitcher: typeof import("../front-end/components/oo/DarkModeSwitcher.vue")['default']
export const LazyOoWeb3ConnectionInfo: typeof import("../front-end/components/oo/Web3ConnectionInfo.vue")['default']
export const LazyOooNFTCollection: typeof import("../front-end/components/ooo/NFTCollection.vue")['default']
export const LazyOooNftCollectionPieces: typeof import("../front-end/components/ooo/NftCollectionPieces.vue")['default']
export const LazyOooPieces: typeof import("../front-end/components/ooo/Pieces.vue")['default']
export const LazyOooPiecesData: typeof import("../front-end/components/ooo/piecesData.ts")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const componentNames: string[]
