/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MessagePortal } from "./MessagePortal";
export * as factories from "./factories";
export { MessagePortal__factory } from "./factories/MessagePortal__factory";
